### ISSUE TITLE
I can resize each panel in the editor by dragging and dropping the divider

### ISSUE THREAD

**Issue by nickeyvee** [chingu-voyages/v11-geckos-team-01#14]
![editor](https://user-images.githubusercontent.com/20284107/65046438-a0bd6300-d92e-11e9-844d-caf1971b45fa.png)

- [You can use React DnD for this](https://react-dnd.github.io/react-dnd/about)

**Comment by pablowbk** [comment]
getting there...

https://codepen.io/pablowbk/pen/bGbxZoz?editors=0011
